<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ArxisStudio.Markup.Xaml.Loader.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/ArxisStudio.Markup.Xaml.Loader/ArxisStudio.Markup.Xaml.Loader.csproj" />
    <ProjectReference Include="../ArxisStudio.Markup.Xaml.Loader.TestControls/ArxisStudio.Markup.Xaml.Loader.TestControls.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Avalonia.Headless.XUnit" />
  </ItemGroup>

</Project>
