<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ArxisStudio.Markup.Benchmarks</RootNamespace>
    <!-- BenchmarkDotNet requires optimised builds to produce meaningful numbers. -->
    <Optimize Condition="'$(Configuration)' == 'Release'">true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/ArxisStudio.Markup.Xaml/ArxisStudio.Markup.Xaml.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

</Project>
